// export const UNAUTH_USER_LIKE_RECIPE = 'UNAUTH_USER_LIKE_RECIPE';
// export const UNAUTH_USER_REMOVE_RECIPE = 'UNAUTH_USER_REMOVE_RECIPE';
export const USER_LOGIN = 'USER_LOGIN';

export const USER_SIGNUP = 'USER_SIGNUP';
export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_RECIPES = 'USER_RECIPES';
export const USER_LIKE_RECIPE = 'USER_LIKE_RECIPE';
export const USER_UNLIKE_RECIPE = 'USER_UNLIKE_RECIPE';

export const NEXT_HOME_PAGINATION = 'NEXT_HOME_PAGINATION';
