export const LOAD_RECIPES = 'LOAD_RECIPES';

export const USER_LOGIN = 'USER_LOGIN';
// export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_SIGNUP = 'USER_SIGNUP';
export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_RECIPES = 'USER_RECIPES';
// export const USER_LIKE_RECIPE = 'USER_LIKE_RECIPE';

export const NEXT_HOME_PAGINATION = 'NEXT_HOME_PAGINATION';
